//use export so that it is accessible in the main js code
//note that export only works for modules, i.e. in the html code, the js scripts must have type="module"
//hardcoded for the upgrade tree (upgradeTo property is needed to decide which tank to grey out)
//IF CHANGE STUFF IN THE SERVER, REMEMBER TO CHANGE HERE TOO
//this is only used for upgrade tree, NOT buttons and the actual game
//tank names with hyphen need inverted commas, e.g. "auto-guard"
//note: asset sizes are relative to player's size, e.g. 0.5 means half of player's size

export const bodyUpgradeMap = [//in the order in which it appears on upgrade tree
  ['base'],
  ['smasher','wall','sentry','hangar','hearth'],
  ['fortress','spike','armory','stronghold','citadel','turret','warship','mender','hail','bonfire'],
  ['castle','palace','thorn','forge','brigade','artillery','triplet','battleship','remedy','blizzard','flare'],
  ['ziggurat','bombard','saw','bastion','battalion','foundry','quadruplet','mothership','fabricator','snowstorm','juggernaut','inferno'],
]

export const weaponUpgradeMap = [
  ['node'],
  ['mono','commander','trapper'],
  ['duo','flank','split','single','alloy','guard','sniper','overseer','director','fusion','gamma','blockade','rubble'],
  ['trio','quad','arc','gunner','overlord','conglomerate','wake','spread','stream','destroyer','assassin','compound','factory','manager','beta','engineer','barricade','stockade','scrap'],
  ['knockback','quadro','penta','streamliner','industry','octo','horizon','disperse','minigun','emperor','hatcher','amalgam','wave','flamethrower','annihilator','manufacturer','hybrid','marksman','executive','alpha','detonator','raider','arsenal','mechanic','riot','palisade','shrapnel'],
]

/*
export const celestialBodyUpgradeMap = [
  ['celestial'],
  ['nebula','chasm','exosphere','corvus','triton'],
  ['naos','galaxy','pollux','void','meteor','comet','heliosphere','cygnus','hyperion','oberon'],
]*/

export const celestialBodyUpgradeMap = [
  ['primordial'],
  ['oven','pounder','chainsaw','lightning','meteor','satellite'],
  ['heliosphere','corvus','chasm','blade','firebolt','nebula','triton'],
]

/*
export const celestialWeaponUpgradeMap = [
  ['nova'],
  ['pulsar','satellite','debris'],
  ['quasar','blazar','moon','synope','asteroid','charon'],
]*/

export const celestialWeaponUpgradeMap = [
  ['eternal'],
  ['hailstorm','bunker','chaos','bombshell','warrior'],
  ['thunderstorm','cosmetic','vault','asteroid','dynamite','mayhem','tarvos','demolisher','veteran'],
]

export const bodyupgrades = {
  //tier 1
  base: {
    upgradeTo: ['smasher','wall','sentry','hangar','hearth'],
  },

  //tier 2
  smasher: { assets: [{ type: "under", sides: 6, color: "#5F676C", outline: "#41494E", size: 1.3, }],
    upgradeTo: ['fortress','spike','armory'],
  },
  wall: { assets: [{ type: "above", sides: 6, color: "default", outline: "default", size: 1.15, }],
    upgradeTo: ['fortress','stronghold','citadel'],
  },
  sentry: {
    turretBaseSize: 0.4,
    bodybarrels: [{ barrelWidth:0.5, barrelHeight:1, additionalAngle:0, x:0, barrelType:"bullet", }],
    upgradeTo:['armory','citadel','turret'],
  },
  hangar:{ bodybarrels: [{ barrelWidth:0.75, barrelHeight:0.75, additionalAngle:0, x:0, barrelType:"drone", }],
    upgradeTo:['warship'],
  },
  hearth: { auraSpecialty: "damaging", auraSize: 4,
    assets: [{ type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.6, }, { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.3, }],
    upgradeTo: ['mender','hail','bonfire'],
  },

  //tier 3
  fortress: { assets: [{ type: "above", sides: 6, color: "#5F676C", outline: "#41494E", size: 1.3, }, { type: "above", sides: 6, color: "default", outline: "default", size: 1, }],
    upgradeTo: ['castle','palace'],
  },
  spike: { assets: [{ type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.6, }],
    upgradeTo: ['castle','thorn','forge'],
  },
  armory: {
    turretBaseSize: 0.4,
    bodybarrels: [{ barrelWidth: 0.5, barrelHeight: 1, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    assets: [{ type: "under", sides: 6, color: "#5F676C", outline: "#41494E", size: 1.3, }],
    upgradeTo: ['castle','brigade'],
  },
  stronghold: { assets: [{ type: "above", sides: 6, color: "default", outline: "default", size: 1.2, }, { type: "above", sides: 6, color: "default", outline: "default", size: 0.6, }],
    upgradeTo: ['castle','palace'],
  },
  citadel: { assets: [{ type: "above", sides: 6, color: "default", outline: "default", size: 1.15, }],
    turretBaseSize: 0.4,
    bodybarrels: [{ barrelWidth:0.5, barrelHeight:1, additionalAngle:0, x:0, barrelType:"bullet", }],
    upgradeTo:['castle'],
  },
  turret:{
    turretBaseSize:0.5,
    bodybarrels: [{ barrelWidth:0.4, barrelHeight:1, additionalAngle:0, x:-0.25, barrelType:"bullet", }, { barrelWidth:0.4, barrelHeight:1, additionalAngle:0, x:0.25, barrelType:"bullet", }],
    upgradeTo:['castle','brigade','artillery','triplet'],
  },
  warship:{ bodybarrels: [{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:0, x:0.9, barrelType:"drone", }, { barrelWidth:0.8, barrelHeight:0.8, additionalAngle:0, x:-0.9, barrelType:"drone", }],
    upgradeTo:['battleship'],
  },
  mender: { auraSpecialty: "heal", auraSize: 6,
    assets: [{ type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.6, }, { type: "above", sides: 8, color: "rgba(56,183,100)", outline: "rgba(26,153,70)", size: 0.3, }],
    upgradeTo: ['remedy'],
  },
  hail: { auraSpecialty: "freeze", auraSize: 5,
    assets: [{ type: "above", sides: 0, color: "rgb(105, 104, 104)", outline: "rgb(79, 78, 78)", size: 0.65, }, { type: "above", sides: 0, color: "rgba(150, 208, 227)", outline: "rgba(132, 190, 209)", size: 0.3, }],
    upgradeTo: ['blizzard'],
  },
  bonfire: { auraSpecialty: "damaging", auraSize: 6,
    assets: [{ type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.7, }, { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.35, }],
    upgradeTo: ['forge','flare'],
  },

  //tier 4
  castle: {
    turretBaseSize: 0.5,
    bodybarrels: [{ barrelWidth: 0.65, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    assets: [{ type: "under", sides: 8, color: "#5F676C", outline: "#41494E", size: 1.45, }, { type: "above", sides: 8, color: "default", outline: "default", size: 1.15, }, { type: "above", sides: 8, color: "default", outline: "default", size: 0.8, }],
    upgradeTo: ['ziggurat','bombard','saw','bastion'],
  },
  palace: { assets: [{ type: "above", sides: 8, color: "default", outline: "default", size: 1.1, }, { type: "above", sides: 6, color: "default", outline: "default", size: 0.8, }],
    upgradeTo: ['ziggurat','bastion'],
  },
  thorn: { assets: [{ type: "under", sides: 5, color: "#5F676C", outline: "#41494E", size: 1.6, angle: -18, }],
    upgradeTo: ['saw','bastion'],
  },
  forge: { auraSpecialty: "damaging", auraSize: 5.5,
    assets: [{ type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.6, }, { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.65, }, { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.325, }],
    upgradeTo: ['foundry'],
  },
  brigade: {
    turretBaseSize: 0.5,
    bodybarrels: [{ barrelWidth:0.4, barrelHeight:1, additionalAngle:0, x:-0.25, barrelType:"bullet", }, { barrelWidth:0.4, barrelHeight:1, additionalAngle:0, x:0.25, barrelType:"bullet", }],
    assets: [{ type: "under", sides: 6, color: "#5F676C", outline: "#41494E", size: 1.4, }],
    upgradeTo: ['bastion','battalion'],
  },
  artillery:{
    turretBaseSize:0.6,
    bodybarrels: [{ barrelWidth:0.8, barrelHeight:1.6, additionalAngle:0, x:0, barrelType:"bullet", }],
    upgradeTo:['bombard','bastion'],
  },
  triplet:{
    turretBaseSize:0.6,
    bodybarrels: [{ barrelWidth:0.5, barrelHeight:1.05, additionalAngle:0, x:-0.3, barrelType:"bullet", }, { barrelWidth:0.5, barrelHeight:1.05, additionalAngle:0, x:0.3, barrelType:"bullet", }, { barrelWidth:0.5, barrelHeight:1.25, additionalAngle:0, x:0, barrelType:"bullet", }],
    upgradeTo:['battalion','quadruplet'],
  },
  battleship:{ bodybarrels: [{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:-30/180*Math.PI, x:0.9, barrelType:"drone", }, { barrelWidth:0.8, barrelHeight:0.8, additionalAngle:-150/180*Math.PI, x:0.9, barrelType:"drone", }, { barrelWidth:0.8, barrelHeight:0.8, additionalAngle: 90/180*Math.PI, x:0.9, barrelType:"drone", }],
    upgradeTo:['mothership'],
  },
  remedy: { auraSpecialty: "heal", auraSize: 7.5,
    assets: [{ type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.75, }, { type: "above", sides: 8, color: "rgba(56,183,100)", outline: "rgba(26,153,70)", size: 0.375, }],
    upgradeTo: ['fabricator'],
  },
  blizzard: { auraSpecialty: "freeze", auraSize: 6,
    assets: [{ type: "above", sides: 0, color: "rgb(105, 104, 104)", outline: "rgb(79, 78, 78)", size: 0.65, }, { type: "above", sides: 0, color: "rgba(150, 208, 227)", outline: "rgba(132, 190, 209)", size: 0.3, }],
    upgradeTo: ['snowstorm','juggernaut'],
  },
  flare: { auraSpecialty: "damaging", auraSize: 7,
    assets: [{ type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.8, }, { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.4, }],
    upgradeTo: ['foundry','juggernaut','inferno'],
  },

  //tier 5
  ziggurat: { assets:[{ type:"above", sides:8, color:"default", outline:"default", size:1.1, }, { type:"above", sides:6, color:"default", outline:"default", size:0.8, }, { type:"above", sides:4, color:"default", outline:"default", size:0.4, }],
    upgradeTo:[],
  },
  bombard:{
    turretBaseSize: 0.8,
    bodybarrels: [{ barrelWidth:1.1, barrelHeight:2, additionalAngle:0, x:0, barrelType:"bullet", }],
    upgradeTo:[],
  },
  saw: { assets: [{ type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.8, }],
    upgradeTo: [],
  },
  bastion:{ assets: [{ type: "under", sides: 5, color: "#5F676C", outline: "#41494E", size: 1.9, angle: -18, }, { type: "above", sides: 8, color: "default", outline: "default", size: 1.3, }, { type: "above", sides: 6, color: "default", outline: "default", size: 0.9, }],
    turretBaseSize:0.6,
    bodybarrels: [{ barrelWidth:0.8, barrelHeight:1.4, additionalAngle:0, x:0, barrelType:"bullet", }],
    upgradeTo:[],
  },
  battalion: {
    turretBaseSize: 0.6,
    bodybarrels: [{ barrelWidth:0.5, barrelHeight:1.05, additionalAngle:0, x:-0.3, barrelType:"bullet", }, { barrelWidth:0.5, barrelHeight:1.05, additionalAngle:0, x:0.3, barrelType:"bullet", }, { barrelWidth:0.5, barrelHeight:1.25, additionalAngle:0, x:0, barrelType:"bullet", }],
    assets: [{ type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.6, }],
    upgradeTo: [],
  },
  foundry: { auraSpecialty: "damaging", auraSize: 6,
    assets: [{ type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.6, }, { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.75, }, { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.375, }],
    upgradeTo: [],
  },
  quadruplet:{
    turretBaseSize:0.65,
    bodybarrels: [{ barrelWidth:0.4, barrelHeight:1.4, additionalAngle:0, x:0.4, barrelType:"bullet", }, { barrelWidth:0.4, barrelHeight:1.4, additionalAngle:0, x:-0.4, barrelType:"bullet", }, { barrelWidth:0.4, barrelHeight:1.1, additionalAngle:0, x:-0.2, barrelType:"bullet", }, { barrelWidth:0.4, barrelHeight:1.1, additionalAngle:0, x:0.2, barrelType:"bullet", }],
    upgradeTo:[],
  },
  mothership:{ bodybarrels: [{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:45/180*Math.PI, x:0.9, barrelType:"drone", }, { barrelWidth:0.8, barrelHeight:0.8, additionalAngle:-45/180*Math.PI, x:0.9, barrelType:"drone", }, { barrelWidth:0.8, barrelHeight:0.8, additionalAngle:135/180*Math.PI, x:0.9, barrelType:"drone", }, { barrelWidth:0.8, barrelHeight:0.8, additionalAngle:-135/180*Math.PI, x:0.9, barrelType:"drone", }],
    upgradeTo:[],
  },
  fabricator: { auraSpecialty: "heal", auraSize: 8,
    assets: [{ type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.9, }, { type: "above", sides: 8, color: "rgba(56,183,100)", outline: "rgba(26,153,70)", size: 0.45, }],
    upgradeTo: [],
  },
  snowstorm: { auraSpecialty: "freeze", auraSize: 8,
    assets: [{ type: "above", sides: 0, color: "rgb(105, 104, 104)", outline: "rgb(79, 78, 78)", size: 0.9, }, { type: "above", sides: 0, color: "rgba(150, 208, 227)", outline: "rgba(132, 190, 209)", size: 0.45, }],
    upgradeTo: [],
  },
  juggernaut: { auraSpecialty: "attraction", auraSize: 8,
    assets: [{ type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.9, }, { type: "above", sides: 0, color: "rgba(120, 118, 194)", outline: "rgba(90, 88, 164)", size: 0.45, }],
    upgradeTo: [],
  },
  inferno: { auraSpecialty: "damaging", auraSize: 8,
    assets: [{ type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.9, }, { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.45, }],
    upgradeTo: [],
  },

  //ETERNALS

  oven:{ eternal:"yes", assets:[{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.7, }, { type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.4, }],
    upgradeTo:['heliosphere','corvus'],
  },
  chainsaw:{ eternal:"yes", assets:[{ type:"under", sides:8, color:"grey", outline:"dimgrey", outlineThickness:5, size:1.2, }],
    upgradeTo:['blade'],
  },
  blade:{ eternal:"yes", assets:[{ type:"under", sides:8, color:"#383838", outline:"black", outlineThickness:5, size:1.3, }],
    upgradeTo:[],
  },
  pounder:{ eternal:"yes", assets:[{ type:"under", sides:6, color:"rgb(35,35,35)", outline:"black", outlineThickness:5, size:1.2, }],
    upgradeTo:['chasm'],
  },
  lightning:{ eternal:"yes", assets:[{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.5, }],
    upgradeTo:['firebolt'],
  },
  meteor:{ eternal:"yes", turretBaseSize:0.6, bodybarrels: [{ barrelWidth:0.5, barrelHeight:1.2, additionalAngle:0, x:-0.3, barrelType:"bullet", }, { barrelWidth:0.5, barrelHeight:1.2, additionalAngle:0, x:0.3, barrelType:"bullet", }],
    upgradeTo:['nebula'],
  },
  satellite:{ eternal:"yes", bodybarrels: [{ barrelWidth:0.7, barrelHeight:0.7, additionalAngle:0, x:0, barrelType:"drone", }],
    upgradeTo:['triton'],
  },
  heliosphere:{ eternal:"yes", assets:[{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.4, angle:0, x:0, y:0, }, { type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.2, angle:0, x:0, y:0, }, { type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.2, angle:0, x:0.7, y:0, }, { type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.1, angle:0, x:0.7, y:0, }, { type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.2, angle:0, x:-0.4, y:-0.6, }, { type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.1, angle:0, x:-0.4, y:-0.6, }, { type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.2, angle:0, x:-0.4, y:0.6, }, { type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.1, angle:0, x:-0.4, y:0.6, }],
    upgradeTo:[],
  },
  corvus:{ eternal:"yes", assets:[{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.8, }, { type:"above", sides:8, color:"rgba(56,183,100)", outline:"rgba(26,153,70)", outlineThickness:5, size:0.5, }],
    upgradeTo:[],
  },
  firebolt:{ eternal:"yes", assets:[{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.6, angle:0, x:0, y:0, }],
    upgradeTo:[],
  },
  chasm:{ eternal:"yes", assets:[{ type:"under", sides:6, color:"#383838", outline:"black", outlineThickness:5, size:1.3, angle:0, x:0, y:0, }, { type:"above", sides:6, color:"default", outline:"default", outlineThickness:5, size:0.7, angle:0, x:0, y:0, }],
    upgradeTo:[],
  },
  nebula:{ eternal:"yes", turretBaseSize:0.6, bodybarrels: [{ barrelWidth:0.5, barrelHeight:1.2, additionalAngle:0, x:-0.3, barrelType:"bullet", }, { barrelWidth:0.5, barrelHeight:1.2, additionalAngle:0, x:0.3, barrelType:"bullet", }, { barrelWidth:0.5, barrelHeight:1.4, additionalAngle:0, x:0, barrelType:"bullet", }],
    upgradeTo:[],
  },
  triton:{ eternal:"yes", bodybarrels: [{ barrelWidth:1, barrelHeight:1, additionalAngle:0, x:0, barrelType:"drone", }],
    upgradeTo:[],
  },
  primordial:{ eternal:"yes",
    upgradeTo:['oven','pounder','chainsaw','lightning','meteor','satellite'],
  },

  //DEV UPGRADES
  ball: { dev: "yes", upgradeTo:[],},
  mario: {dev: "yes",
    assets: [{ "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 5, "size": 1, "angle": 45, "x": 0, "y": 0 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 5, "size": 1, "angle": 45, "x": 1, "y": 1 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 5, "size": 1, "angle": 45, "x": 2, "y": 0 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 5, "size": 1, "angle": 45, "x": -1, "y": -1 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": -2 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": -3 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": 0, "y": -4 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": 0 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": 1 }, { "type": "above", "sides": 4, "color": "#f8a902", "outline": "#f8a902", "outlineThickness": 0, "size": 1, "angle": 45, "x": -3, "y": -1 }, { "type": "above", "sides": 4, "color": "#f8a902", "outline": "#f8a902", "outlineThickness": 0, "size": 1, "angle": 45, "x": 0, "y": 2 }, { "type": "above", "sides": 4, "color": "#f8a902", "outline": "#f8a902", "outlineThickness": 5, "size": 1, "angle": 45, "x": 0, "y": 2 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": 3 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": 3 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": 0, "y": 4 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": 3 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": 2 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -3, "y": 1 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -4, "y": 0 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -5, "y": -1 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -4, "y": -2 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -4, "y": -2 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -5, "y": 1 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -6, "y": 0 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -7, "y": -1 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -4, "y": 2 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -3, "y": 3 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": 4 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": 5 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": 0, "y": 6 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": 7 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": 6 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -3, "y": 5 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -6, "y": 2 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -6, "y": 2 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -7, "y": 1 }, { "type": "above", "sides": 4, "color": "#d70202", "outline": "#d70202", "outlineThickness": 0, "size": 1, "angle": 45, "x": -8, "y": 0 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -9, "y": 1 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -10, "y": 0 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -8, "y": 2 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -3, "y": 7 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": 8 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": 9 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": 11 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": 10 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -3, "y": 9 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -4, "y": 8 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -9, "y": 3 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -9, "y": 3 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -10, "y": 2 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -11, "y": 1 }, { "type": "above", "sides": 4, "color": "#706700", "outline": "#706700", "outlineThickness": 0, "size": 1, "angle": 45, "x": -12, "y": 0 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": -8, "y": -2 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": -9, "y": -3 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": -6, "y": -2 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": -7, "y": -3 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": -8, "y": -4 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": -7, "y": -5 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": -6, "y": -4 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": 5 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": 5 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": 6 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": 7 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": 6 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": 8 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": 7 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": 4 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -5, "y": -3 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -3, "y": -3 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -4, "y": -4 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -5, "y": -5 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -6, "y": -6 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -4, "y": -6 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -3, "y": -5 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": -4 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": -5 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": -2, "y": -6 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": 2 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": 3 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": 4 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 5, "y": 5 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 5, "y": 3 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": 2 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": 1 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": -1 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 0, "y": -2 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": -2 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": -1 }, { "type": "above", "sides": 4, "color": "#706602", "outline": "#706602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": -3 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": -3 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": -2 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 5, "y": -1 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 6, "y": 0 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 0, "y": -6 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": -5 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": -4 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": -7 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": -6 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": -5 }, { "type": "above", "sides": 4, "color": "#f6aa07", "outline": "#f6aa07", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": -4 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 5, "y": -3 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 6, "y": -2 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 7, "y": -1 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 8, "y": 0 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 0, "y": -8 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": -1, "y": -9 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 0, "y": -10 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": -8 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": -9 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": -8 }, { "type": "above", "sides": 4, "color": "#706702", "outline": "#706702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": -7 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": -6 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 5, "y": -5 }, { "type": "above", "sides": 4, "color": "#f7aa06", "outline": "#f7aa06", "outlineThickness": 0, "size": 1, "angle": 45, "x": 6, "y": -4 }, { "type": "above", "sides": 4, "color": "#716602", "outline": "#716602", "outlineThickness": 0, "size": 1, "angle": 45, "x": 7, "y": -3 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 8, "y": -2 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 9, "y": -1 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 10, "y": 0 }, { "type": "above", "sides": 4, "color": "#6e6702", "outline": "#6e6702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 1, "y": -11 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": -10 }, { "type": "above", "sides": 4, "color": "#6e6702", "outline": "#6e6702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": -9 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 2, "y": -10 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": -8 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 5, "y": -7 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 6, "y": -6 }, { "type": "above", "sides": 4, "color": "#6e6702", "outline": "#6e6702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 7, "y": -5 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 8, "y": -4 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 9, "y": -3 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 10, "y": -2 }, { "type": "above", "sides": 4, "color": "#6e6702", "outline": "#6e6702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 3, "y": -11 }, { "type": "above", "sides": 4, "color": "#6e6702", "outline": "#6e6702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": -10 }, { "type": "above", "sides": 4, "color": "#6e6702", "outline": "#6e6702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 5, "y": -9 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 6, "y": -8 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 7, "y": -7 }, { "type": "above", "sides": 4, "color": "#6e6702", "outline": "#6e6702", "outlineThickness": 0, "size": 1, "angle": 45, "x": 8, "y": -6 }, { "type": "above", "sides": 4, "color": "#f8a90d", "outline": "#f8a90d", "outlineThickness": 0, "size": 1, "angle": 45, "x": 9, "y": -5 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 4, "y": -12 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 5, "y": -11 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 6, "y": -10 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 7, "y": -9 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 8, "y": -8 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 9, "y": -7 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 10, "y": -6 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 11, "y": -5 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 12, "y": -4 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 6, "y": -12 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 7, "y": -11 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 8, "y": -10 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 9, "y": -9 }, { "type": "above", "sides": 4, "color": "#d70205", "outline": "#d70205", "outlineThickness": 0, "size": 1, "angle": 45, "x": 10, "y": -8 }],
    upgradeTo:[],},
};


export const weaponupgrades = {//barrelwidth and barrelheight seems to be twice the value of scenexe's, except trap, drone, and mine barrel widths are the same, and minion barrels are... weird (figure out scenexe's rendering later) (rocketer minion barrel width should be 1.5 times of scenexe most of the time)
  //unlike body barrels, weapon barrels are in terms of degree for angle, not radians
  //ALSO remember all barrels need to have different names, or else only one will render
  //tier 1
  node: { barrels: [],
    upgradeTo: ['mono','commander','trapper'],
  },
  //tier 2
  mono: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['duo','flank','split','single','alloy','guard','sniper'],
  },
  commander: { barrels: [{ barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "drone", }],
    upgradeTo: ['alloy','overseer','director','fusion'],
  },
  trapper: { barrels: [{ barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }],
    upgradeTo: ['guard','fusion','gamma','blockade','rubble'],
  },
  //tier 3
  duo: { barrels: [{ barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0.5, barrelType: "bullet", }],
    upgradeTo: ['trio','quad','arc','gunner'],
  },
  flank: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "bullet", }],
    upgradeTo: ['quad','overlord','conglomerate','wake'],
  },
  split: { barrels: [{ barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: -35, x: 0, barrelType: "bullet", }, { barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: 35, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['trio','quad','arc','gunner','spread'],
  },
  single: { barrels: [{ barrelWidth: 1.4, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['stream','destroyer','assassin','compound'],
  },
  alloy: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }],
    upgradeTo: ['conglomerate','compound'],
  },
  guard: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }],
    upgradeTo: ['conglomerate','wake'],
  },
  sniper: { barrels: [{ barrelWidth: 1, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['wake','destroyer','assassin'],
  },
  overseer: { barrels: [{ barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }],
    upgradeTo: ['overlord','factory'],
  },
  director: { barrels: [{ barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "drone", }],
    upgradeTo: ['compound','manager'],
  },
  fusion: { barrels: [{ barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }],
    upgradeTo: ['conglomerate'],
  },
  gamma: { barrels: [{ barrelWidth: 0.85, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }],
    upgradeTo: ['beta','engineer'],
  },
  blockade: { barrels: [{ barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }],
    upgradeTo: ['conglomerate','barricade','stockade'],
  },
  rubble: { barrels: [{ barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 90, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 270, x: 0, barrelType: "trap", }],
    upgradeTo: ['scrap'],
  },
  //tier 4
  trio: { barrels: [{ barrelWidth: 0.8, barrelHeight: 1.6, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.6, additionalAngle: 0, x: 0.5, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['knockback','quadro','penta','streamliner','industry'],
  },
  quad: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 270, x: 0, barrelType: "bullet", }],
    upgradeTo: ['octo','horizon'],
  },
  arc: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 45, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: -45, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: -90, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['penta','octo','horizon','disperse'],
  },
  gunner: { barrels: [{ barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: -0.3, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: 0.3, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.2, additionalAngle: 0, x: -0.8, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.2, additionalAngle: 0, x: 0.8, barrelType: "bullet", }],
    upgradeTo: ['quadro','streamliner','horizon','minigun'],
  },
  overlord: { barrels: [{ barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: -120, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 120, x: 0, barrelType: "drone", }],
    upgradeTo: ['emperor','hatcher'],
  },
  conglomerate: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 120, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: -120, x: 0, barrelType: "drone", }],
    upgradeTo: ['amalgam'],
  },
  wake: { barrels: [{ barrelWidth: 0.8, barrelHeight: 1.8, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, { barrelWidth: 1, barrelHeight: 1.6, additionalAngle: -140, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.6, additionalAngle: 140, x: 0, barrelType: "bullet", }],
    upgradeTo: ['wave'],
  },
  spread: { barrels: [{ barrelWidth: .5, barrelHeight: 1.4, additionalAngle: -60, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.4, additionalAngle: 60, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 40, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: -40, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: 20, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: -20, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['penta','horizon','disperse'],
  },
  stream: { barrels: [{ barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['flamethrower'],
  },
  destroyer: { barrels: [{ barrelWidth: 1.6, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['annihilator','manufacturer','hybrid'],
  },
  assassin: { barrels: [{ barrelWidth: 1, barrelHeight: 2.5, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: ['streamliner','marksman'],
  },
  compound: { barrels: [{ barrelWidth: 1.4, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: .7, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }],
    upgradeTo: ['hybrid'],
  },
  factory: { barrels: [{ barrelWidth: .75, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "minion", }],
    upgradeTo: ['industry','manufacturer','hatcher'],
  },
  manager: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "drone", }],
    upgradeTo: ['manufacturer','hybrid','executive'],
  },
  beta: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }],
    upgradeTo: ['alpha','raider'],
  },
  engineer: { barrels: [{ barrelWidth: .75, barrelHeight: 1.9, additionalAngle: 0, x: 0, barrelType: "mine", }],
    upgradeTo: ['raider','arsenal','mechanic','detonator'],
  },
  barricade: { barrels: [{ barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }],
    upgradeTo: ['wave','arsenal','riot'],
  },
  stockade: { barrels: [{ barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 120, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: -120, x: 0, barrelType: "trap", }],
    upgradeTo: ['mechanic','palisade'],
  },
  scrap: { barrels: [{ barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 60, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 300, x: 0, barrelType: "trap", }],
    upgradeTo: ['shrapnel'],
  },
  //tier 5
  knockback: { barrels: [{ barrelWidth: 0.8, barrelHeight: 1.5, additionalAngle: 0, x: -0.6, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.5, additionalAngle: 0, x: 0.6, barrelType: "bullet", }],
    upgradeTo: [],
  },
  quadro: { barrels: [{ barrelWidth: 0.6, barrelHeight: 2, additionalAngle: 0, x: 0.65, barrelType: "bullet", }, { barrelWidth: 0.6, barrelHeight: 2, additionalAngle: 0, x: -0.65, barrelType: "bullet", }, { barrelWidth: 0.6, barrelHeight: 1.6, additionalAngle: 0, x: 0.3, barrelType: "bullet", }, { barrelWidth: 0.6, barrelHeight: 1.6, additionalAngle: 0, x: -0.3, barrelType: "bullet", }],
    upgradeTo: [],
  },
  penta: { barrels: [{ barrelWidth: 1, barrelHeight: 1.6, additionalAngle: 40, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.6, additionalAngle: -40, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: 20, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: -20, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  streamliner: { barrels: [{ barrelWidth: 0.8, barrelHeight: 2.6, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 2.4, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.8, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.4, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  industry: { barrels: [{ barrelWidth: .7, barrelHeight: 2.2, additionalAngle: 0, x: -0.5, barrelType: "minion", }, { barrelWidth: .7, barrelHeight: 2.2, additionalAngle: 0, x: 0.5, barrelType: "minion", }],
    upgradeTo: [],
  },
  octo: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 45, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 135, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 225, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 270, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 315, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  horizon: { barrels: [{ barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 22.5, x: 0, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: -22.5, x: 0, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 45, x: 0, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: -45, x: 0, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 67.5, x: 0, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: -67.5, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: -90, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  disperse: { barrels: [{ barrelWidth: .5, barrelHeight: 1.4, additionalAngle: -75, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.4, additionalAngle: 75, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: -60, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 60, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: -45, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: 45, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 2, additionalAngle: -30, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 2, additionalAngle: 30, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 2.2, additionalAngle: -15, x: 0, barrelType: "bullet", }, { barrelWidth: .5, barrelHeight: 2.2, additionalAngle: 15, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 2.4, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  minigun: { barrels: [{ barrelWidth: 0.4, barrelHeight: 2.4, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 2.4, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 2.4, additionalAngle: 0, x: 0.5, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: 0.5, barrelType: "bullet", }],
    upgradeTo: [],
  },
  emperor: { barrels: [{ barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: -90, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 90, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }],
    upgradeTo: [],
  },
  hatcher: { barrels: [{ barrelWidth: .5, barrelHeight: 1.8, additionalAngle: 0, x: 0, barrelType: "minion", }, { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: 120, x: 0, barrelType: "minion", }, { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: -120, x: 0, barrelType: "minion", }],
    upgradeTo: [],
  },
  amalgam: { barrels: [{ barrelWidth: .8, barrelHeight: 2, additionalAngle: 0, x: 0.5, barrelType: "bullet", }, { barrelWidth: .8, barrelHeight: 2, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, { barrelWidth: .65, barrelHeight: 1.5, additionalAngle: -15, x: -0.4, barrelType: "trap", }, { barrelWidth: .65, barrelHeight: 1.5, additionalAngle: 15, x: 0.4, barrelType: "trap", }, { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 140, x: 0, barrelType: "drone", }, { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: -140, x: 0, barrelType: "drone", }],
    upgradeTo: [],
  },
  wave: { barrels: [{ barrelWidth: 1, barrelHeight: 1.8, additionalAngle: -150, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: 150, x: 0, barrelType: "bullet", }, { barrelWidth: .65, barrelHeight: 2.1, additionalAngle: 180, x: 0, barrelType: "trap", }, { barrelWidth: .65, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "trap", }, { barrelWidth: .8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  flamethrower: { barrels: [{ barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  annihilator: { barrels: [{ barrelWidth: 2, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  manufacturer: { barrels: [{ barrelWidth: 1.1, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "minion", }],
    upgradeTo: [],
  },
  hybrid: { barrels: [{ barrelWidth: 1.6, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }],
    upgradeTo: [],
  },
  marksman: { barrels: [{ barrelWidth: 1, barrelHeight: 2.8, additionalAngle: 0, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  executive: { barrels: [{ barrelWidth: 1.5, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "drone", }],
    upgradeTo: [],
  },
  alpha: { barrels: [{ barrelWidth: 1.5, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }],
    upgradeTo: [],
  },
  detonator: { barrels: [{ barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "mine", }],
    upgradeTo: [],
  },
  raider: { barrels: [{ barrelWidth: .9, barrelHeight: 1.7, additionalAngle: 0, x: 0, barrelType: "mine", }],
    upgradeTo: [],
  },
  arsenal: { barrels: [{ barrelWidth: .6, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "mine", }, { barrelWidth: .6, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "mine", }],
    upgradeTo: [],
  },
  mechanic: { barrels: [{ barrelWidth: .55, barrelHeight: 1.7, additionalAngle: 0, x: 0, barrelType: "mine", }, { barrelWidth: .55, barrelHeight: 1.7, additionalAngle: 120, x: 0, barrelType: "mine", }, { barrelWidth: .55, barrelHeight: 1.7, additionalAngle: -120, x: 0, barrelType: "mine", }],
    upgradeTo: [],
  },
  riot: { barrels: [{ barrelWidth: 0.65, barrelHeight: 2.5, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }],
    upgradeTo: [],
  },
  palisade: { barrels: [{ barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: -90, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "trap", }, { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }],
    upgradeTo: [],
  },
  shrapnel: { barrels: [{ barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 45, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 90, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 135, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 225, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 270, x: 0, barrelType: "trap", }, { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 315, x: 0, barrelType: "trap", }],
    upgradeTo: [],
  },

  //ETERNALS

  hailstorm: { eternal: "yes", barrels: [{ barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 120, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 240, x: 0, barrelType: "bullet", }],
    upgradeTo: ['thunderstorm','cosmetic'],
  },
  bunker: { eternal: "yes", barrels: [{ barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, { barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "trap", }, { barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "trap", }],
    upgradeTo: ['vault','asteroid','dynamite'],
  },
  chaos: { eternal: "yes", barrels: [{ barrelWidth: 0.75, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.35, additionalAngle: 0, x: 0, barrelType: "drone", }, { barrelWidth: 0.75, barrelHeight: 1.2, additionalAngle: 120, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.35, additionalAngle: 120, x: 0, barrelType: "drone", }, { barrelWidth: 0.75, barrelHeight: 1.2, additionalAngle: 240, x: 0, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.35, additionalAngle: 240, x: 0, barrelType: "drone", }],
    upgradeTo: ['mayhem','tarvos'],
  },
  bombshell: { eternal: "yes", barrels: [{ barrelWidth: 1.5, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 1.5, barrelHeight: 1.2, additionalAngle: 120, x: 0, barrelType: "bullet", }, { barrelWidth: 1.5, barrelHeight: 1.2, additionalAngle: 240, x: 0, barrelType: "bullet", }],
    upgradeTo: ['demolisher'],
  },
  warrior: { eternal: "yes", barrels: [{ barrelWidth: 0.9, barrelHeight: 1.4, additionalAngle: 0, x: 0, barrelType: "drone", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: 120, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: -120, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.8, additionalAngle: 180, x: 0, barrelType: "trap", }],
    upgradeTo: ['veteran'],
  },
  thunderstorm: { eternal: "yes", barrels: [{ barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 180, x: 0, barrelType: "bullet", }, { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 60, x: 0, barrelType: "bullet", }, { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 120, x: 0, barrelType: "bullet", }, { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 240, x: 0, barrelType: "bullet", }, { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 300, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  cosmetic: { eternal: "yes", barrels: [{ barrelWidth: 0.9, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "bullet", }, { barrelWidth: 0.9, barrelHeight: 1.6, additionalAngle: 60, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.3, additionalAngle: 120, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.3, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.3, additionalAngle: 240, x: 0, barrelType: "bullet", }, { barrelWidth: 0.9, barrelHeight: 1.6, additionalAngle: 300, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  vault: { eternal: "yes", barrels: [{ barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 60, x: 0, barrelType: "trap", }, { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 120, x: 0, barrelType: "trap", }, { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 180, x: 0, barrelType: "trap", }, { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 240, x: 0, barrelType: "trap", }, { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 300, x: 0, barrelType: "trap", }, { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "trap", }],
    upgradeTo: [],
  },
  asteroid: { eternal: "yes", barrels: [{ barrelWidth: 0.65, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "mine", }, { barrelWidth: 0.65, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "mine", }, { barrelWidth: 0.65, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "mine", }],
    upgradeTo: [],
  },
  mayhem: { eternal: "yes", barrels: [{ barrelWidth: 0.2, barrelHeight: 1.6, additionalAngle: 0, x: 0.25, barrelType: "drone", }, { barrelWidth: 0.2, barrelHeight: 1.6, additionalAngle: 0, x: -0.25, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 60, x: 0, barrelType: "drone", }, { barrelWidth: 0.2, barrelHeight: 1.6, additionalAngle: 120, x: 0.25, barrelType: "drone", }, { barrelWidth: 0.2, barrelHeight: 1.6, additionalAngle: 120, x: -0.25, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }, { barrelWidth: 0.2, barrelHeight: 1.6, additionalAngle: 240, x: 0.25, barrelType: "drone", }, { barrelWidth: 0.2, barrelHeight: 1.6, additionalAngle: 240, x: -0.25, barrelType: "drone", }, { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 300, x: 0, barrelType: "drone", }],
    upgradeTo: [],
  },
  dynamite: { eternal: "yes", barrels: [{ barrelWidth: 0.75, barrelHeight: 1.1, additionalAngle: 0, x: 0, barrelType: "mine", }, { barrelWidth: 0.75, barrelHeight: 1.1, additionalAngle: 120, x: 0, barrelType: "mine", }, { barrelWidth: 0.75, barrelHeight: 1.1, additionalAngle: 240, x: 0, barrelType: "mine", }],
    upgradeTo: [],
  },
  tarvos: { eternal: "yes", barrels: [{ barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "minion", }, { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "minion", }, { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "minion", }],
    upgradeTo: [],
  },
  demolisher: { eternal: "yes", barrels: [{ barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 60, x: 0, barrelType: "bullet", }, { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 120, x: 0, barrelType: "bullet", }, { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 180, x: 0, barrelType: "bullet", }, { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 240, x: 0, barrelType: "bullet", }, { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 300, x: 0, barrelType: "bullet", }],
    upgradeTo: [],
  },
  veteran: { eternal: "yes", barrels: [{ barrelWidth: 0.7, barrelHeight: 1.4, additionalAngle: 20, x: 0, barrelType: "drone", }, { barrelWidth: 0.7, barrelHeight: 1.4, additionalAngle: -20, x: 0, barrelType: "drone", }, { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 125, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 155, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: -125, x: 0, barrelType: "bullet", }, { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: -155, x: 0, barrelType: "bullet", }, { barrelWidth: 0.8, barrelHeight: 1.8, additionalAngle: 180, x: 0, barrelType: "trap", }],
    upgradeTo: [],
  },
  eternal: { eternal: "yes",
    upgradeTo: ['hailstorm','bunker','chaos','bombshell','warrior'],
  },

  //DEV UPGRADES
  gun: { dev: "yes", barrels: [{barrelWidth: 0.56, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet",}],
    upgradeTo: [],
  },
  surveyor: { dev: "yes", upgradeTo: [],},
  ring: { dev: "yes", barrels: [{barrelWidth: 1, barrelHeight: 2, additionalAngle: 30, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 60, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 120, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 150, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 210, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 240, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 270, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 300, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 330, x: 0, barrelType: "bullet",}, {barrelWidth: 1, barrelHeight: 2, additionalAngle: 360, x: 0, barrelType: "bullet",},],
    upgradeTo: [],
  },
};

export const bodyColors = {//side note: color when hit or have spawn protection has values in RGB is 20 higher)
  blue: {
    col: "#00B0E1",
    outline: "#0092C3",
  },
  green: {
    col: "#00E06C",
    outline: "#00C24E",
  },
  red: {
    col: "#F04F54",
    outline: "#b33b3f",
  },
  purple: {
    col: "#BE7FF5",
    outline: "#A061D7",
  },
  magenta: {
    col: "#D82BCF",
    outline: "#BA0DB1",
  },
  fallen: {
    col: "#C0C0C0",
    outline: "#A2A2A2",
  },
  eternal: {
    col: "#841e84",//changed from 934c93
    outline: "#660066",
  },
  celestial: {
    col: "#F177DD",
    outline: "#D359BF",
  },
  barrel: {
    col: "#999999",
    outline: "#7B7B7B",
  },
  asset: {
    col: "#5F676C",
    outline: "#41494E",
  },
  triangle: {
    col: "#FFE46B",
    outline: "#E1C64D",
  },
  square: {
    col: "#FC7676",
    outline: "#DE5858",
  },
  pentagon: {
    col: "#768CFC",
    outline: "#586EDE",
  },
  hexagon: {
    col: "#FCA644",
    outline: "#DE8826",
  },
  heptagon: {
    col: "#38B764",
    outline: "#1A9946",
  },
  octagon: {
    col: "#4A66BD",
    outline: "#2C489F",
  },
  nonagon: {
    col: "#5D275D",
    outline: "#3F093F",
  },
  decagon: {
    col: "#1A1C2C",
    outline: "#00000E",
  },
  hendecagon: {
    col: "#060011",
    outline: "#000000",
  },
  dodecagon: {
    col: "#403645",
    outline: "#221827",
  },
  tridecagon: {
    col: "#EDEDFF",
    outline: "#CFCFE1",
  },
  tetradecagon: {
    col: "#000000",
    outline: "#000000",
  },
  transparent: {
    col: "transparent",
    outline: "transparent",
  },
  cyan: {
    col: "#00ffff",
    outline: "#00e1e1"
  },
  brown: {
    col: "#a76f47",
    outline: "#895129"
  }
};


export const botcolors = { //get colors based on dune mob name
  //mobs
  Legion: {color: "#e9ac7a", outline: "#d99b68", level: "30 (mob)",},
  Booster: {color: "#e9ac7a", outline: "#d99b68", level: "30 (mob)",},
  Glutton: {color: "#402d2d", outline: "#220f0f", level: "40 (mob)",},
  //bosses
  Cluster: {color: "#00ffff", outline: "#09d3fb", level: "80 (boss)",},
  Pursuer: {color: "#00ffff", outline: "#09d3fb", level: "50 (minion)",},
  Crasher: {color: "#00ffff", outline: "#09d3fb", level: "15 (minion)",},
  Champion: {color: "#00ffff", outline: "#09d3fb", level: "50 (minion)",},
  Infestor: {color: "#916f6f", outline: "#6c5353", level: "80 (boss)",},//bullet knockback
  Pillbox: {color: "#916f6f", outline: "#6c5353", level: "50 (minion)",},
  Leech: {color: "#916f6f", outline: "#6c5353", level: "50 (minion)",},//lifesteal
  Vulcan: {color: "#19013d", outline: "#00011f", level: "100 (boss)",},
  Oblivion: {color: "#b03333", outline: "#921515", level: "100 (boss)",},
  Bane: {color: "#4d4b4b", outline: "#2f2d2d", level: "100 (boss)",},
  Gravedigger: {color: "#2f2d4b", outline: "#110f2d", level: "100 (boss)",},
  Maw: {color: "#402d4b", outline: "#220f2d", level: "100 (boss)",},
  Monarch: {color: "#3f402d", outline: "#21220f", level: "100 (boss)",},
  //cavern guardians
  "Cavern Protector": {color: "#FFE46B", outline: "#E1C64D", level: "210",},
  "Abyssling": {color: "#FFE46B", outline: "#E1C64D", level: "100",},
  //static mobs
  Rock: {color: "#909090", outline: "#5c5c5c", level: "25 (static)",},
  Gravel: {color: "#909090", outline: "#5c5c5c", level: "10 (static)",},
  Boulder: {color: "#505250", outline: "#000000", level: "45 (static)",},
  Mountain: {color: "#b8683b", outline: "#87563a", level: "60 (static)",},
  Cactus: {color: "#60b560", outline: "#428042", level: "60 (static)",},
  //FFA events
  "Chaos Critters": {color: "#37013d", outline: "#19011f", level: "100",},
  "Slime Blob": {color: "#7bc35c", outline: "#5da53e", level: "60",},
};