//use export so that it is accessible in the main js code
//note that export only works for modules, i.e. in the html code, the js scripts must have type="module"
//hardcoded for the upgrade tree (upgradeTo property is needed to decide which tank to grey out)
//IF CHANGE STUFF IN THE SERVER, REMEMBER TO CHANGE HERE TOO
//this is only used for upgrade tree, NOT buttons and the actual game
//tank names with hyphen need inverted commas, e.g. "auto-guard"
//note: asset sizes are relative to player's size, e.g. 0.5 means half of player's size

export const bodyUpgradeMap = [//in the order in which it appears on upgrade tree
  ['base'],
  ['smasher','wall','sentry','hangar','hearth'],
  ['fortress','spike','armory','stronghold','citadel','turret','warship','mender','hail','bonfire'],
  ['castle','palace','thorn','forge','brigade','artillery','triplet','battleship','remedy','blizzard','flare'],
  ['ziggurat','bombard','saw','bastion','battalion','foundry','quadruplet','mothership','fabricator','snowstorm','juggernaut','inferno'],
]

export const weaponUpgradeMap = [
  ['node'],
  ['mono','commander','trapper'],
  ['duo','flank','split','single','alloy','guard','sniper','overseer','director','fusion','gamma','blockade','rubble'],
  ['trio','quad','arc','gunner','overlord','conglomerate','wake','spread','stream','destroyer','assassin','compound','factory','manager','beta','engineer','barricade','stockade','scrap'],
  ['knockback','quadro','penta','streamliner','industry','octo','horizon','disperse','minigun','emperor','hatcher','amalgam','wave','flamethrower','annihilator','manufacturer','hybrid','marksman','executive','alpha','detonator','raider','arsenal','mechanic','riot','palisade','shrapnel'],
]

/*
export const celestialBodyUpgradeMap = [
  ['celestial'],
  ['nebula','chasm','exosphere','corvus','triton'],
  ['naos','galaxy','pollux','void','meteor','comet','heliosphere','cygnus','hyperion','oberon'],
]*/

export const celestialBodyUpgradeMap = [
  ['primordial'],
  ['oven','pounder','chainsaw','lightning','meteor','satellite'],
  ['heliosphere','corvus','chasm','blade','firebolt','nebula','triton'],
]

/*
export const celestialWeaponUpgradeMap = [
  ['nova'],
  ['pulsar','satellite','debris'],
  ['quasar','blazar','moon','synope','asteroid','charon'],
]*/

export const celestialWeaponUpgradeMap = [
  ['eternal'],
  ['hailstorm','bunker','chaos','bombshell','warrior'],
  ['thunderstorm','cosmetic','vault','asteroid','dynamite','mayhem','tarvos','demolisher','veteran'],
]

export const bodyupgrades = {
  //tier 1
  base: {
    upgradeTo: ['smasher','wall','sentry','hangar','hearth'],
  },

  //tier 2
  smasher: { assets: { assetOne: { type: "under", sides: 6, color: "#5F676C", outline: "#41494E", size: 1.3, }, },
    upgradeTo: ['fortress','spike','armory'],
  },
  wall: { assets: { assetOne: { type: "above", sides: 6, color: "default", outline: "default", size: 1.15, }, },
    upgradeTo: ['fortress','stronghold','citadel'],
  },
  sentry: {
    turretBaseSize: 0.4,
    bodybarrels:{ barrelOne:{ barrelWidth:0.5, barrelHeight:1, additionalAngle:0, x:0, barrelType:"bullet", }, },
    upgradeTo:['armory','citadel','turret'],
  },
  hangar:{ bodybarrels:{ barrelOne:{ barrelWidth:0.75, barrelHeight:0.75, additionalAngle:0, x:0, barrelType:"drone", }, },
    upgradeTo:['warship'],
  },
  hearth: { auraSpecialty: "damaging", auraSize: 4,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.6, }, assetTwo: { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.3, }, },
    upgradeTo: ['mender','hail','bonfire'],
  },

  //tier 3
  fortress: { assets: { assetOne: { type: "above", sides: 6, color: "#5F676C", outline: "#41494E", size: 1.3, }, assetTwo: { type: "above", sides: 6, color: "default", outline: "default", size: 1, }, },
    upgradeTo: ['castle','palace'],
  },
  spike: { assets: { assetOne: { type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.6, }, },
    upgradeTo: ['castle','thorn','forge'],
  },
  armory: {
    turretBaseSize: 0.4,
    bodybarrels: { barrelOne: { barrelWidth: 0.5, barrelHeight: 1, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    assets: { assetOne: { type: "under", sides: 6, color: "#5F676C", outline: "#41494E", size: 1.3, }, },
    upgradeTo: ['castle','brigade'],
  },
  stronghold: { assets: { assetOne: { type: "above", sides: 6, color: "default", outline: "default", size: 1.2, }, assetTwo: { type: "above", sides: 6, color: "default", outline: "default", size: 0.6, }, },
    upgradeTo: ['castle','palace'],
  },
  citadel: { assets: { assetOne: { type: "above", sides: 6, color: "default", outline: "default", size: 1.15, }, },
    turretBaseSize: 0.4,
    bodybarrels:{ barrelOne:{ barrelWidth:0.5, barrelHeight:1, additionalAngle:0, x:0, barrelType:"bullet", }, },
    upgradeTo:['castle'],
  },
  turret:{
    turretBaseSize:0.5,
    bodybarrels:{ barrelOne:{ barrelWidth:0.4, barrelHeight:1, additionalAngle:0, x:-0.25, barrelType:"bullet", }, barrelTwo:{ barrelWidth:0.4, barrelHeight:1, additionalAngle:0, x:0.25, barrelType:"bullet", }, },
    upgradeTo:['castle','brigade','artillery','triplet'],
  },
  warship:{ bodybarrels:{ barrelOne:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:0, x:0.9, barrelType:"drone", }, barrelTwo:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:0, x:-0.9, barrelType:"drone", }, },
    upgradeTo:['battleship'],
  },
  mender: { auraSpecialty: "heal", auraSize: 6,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.6, }, assetTwo: { type: "above", sides: 8, color: "rgba(56,183,100)", outline: "rgba(26,153,70)", size: 0.3, }, },
    upgradeTo: ['remedy'],
  },
  hail: { auraSpecialty: "freeze", auraSize: 5,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(105, 104, 104)", outline: "rgb(79, 78, 78)", size: 0.65, }, assetTwo: { type: "above", sides: 0, color: "rgba(150, 208, 227)", outline: "rgba(132, 190, 209)", size: 0.3, }, },
    upgradeTo: ['blizzard'],
  },
  bonfire: { auraSpecialty: "damaging", auraSize: 6,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.7, }, assetTwo: { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.35, }, },
    upgradeTo: ['forge','flare'],
  },

  //tier 4
  castle: {
    turretBaseSize: 0.5,
    bodybarrels: { barrelOne: { barrelWidth: 0.65, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    assets: { assetOne: { type: "under", sides: 8, color: "#5F676C", outline: "#41494E", size: 1.45, }, assetTwo: { type: "above", sides: 8, color: "default", outline: "default", size: 1.15, }, assetThree: { type: "above", sides: 8, color: "default", outline: "default", size: 0.8, }, },
    upgradeTo: ['ziggurat','bombard','saw','bastion'],
  },
  palace: { assets: { assetOne: { type: "above", sides: 8, color: "default", outline: "default", size: 1.1, }, assetTwo: { type: "above", sides: 6, color: "default", outline: "default", size: 0.8, }, },
    upgradeTo: ['ziggurat','bastion'],
  },
  thorn: { assets: { assetOne: { type: "under", sides: 5, color: "#5F676C", outline: "#41494E", size: 1.6, angle: -18, }, },
    upgradeTo: ['saw','bastion'],
  },
  forge: { auraSpecialty: "damaging", auraSize: 5.5,
    assets: { assetThree: { type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.6, }, assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.65, }, assetTwo: { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.325, }, },
    upgradeTo: ['foundry'],
  },
  brigade: {
    turretBaseSize: 0.5,
    bodybarrels: { barrelOne:{ barrelWidth:0.4, barrelHeight:1, additionalAngle:0, x:-0.25, barrelType:"bullet", }, barrelTwo:{ barrelWidth:0.4, barrelHeight:1, additionalAngle:0, x:0.25, barrelType:"bullet", }, },
    assets: { assetOne: { type: "under", sides: 6, color: "#5F676C", outline: "#41494E", size: 1.4, }, },
    upgradeTo: ['bastion','battalion'],
  },
  artillery:{
    turretBaseSize:0.6,
    bodybarrels:{ barrelOne:{ barrelWidth:0.8, barrelHeight:1.6, additionalAngle:0, x:0, barrelType:"bullet", }, },
    upgradeTo:['bombard','bastion'],
  },
  triplet:{
    turretBaseSize:0.6,
    bodybarrels:{ barrelOne:{ barrelWidth:0.5, barrelHeight:1.05, additionalAngle:0, x:-0.3, barrelType:"bullet", }, barrelTwo:{ barrelWidth:0.5, barrelHeight:1.05, additionalAngle:0, x:0.3, barrelType:"bullet", }, barrelThree:{ barrelWidth:0.5, barrelHeight:1.25, additionalAngle:0, x:0, barrelType:"bullet", },},
    upgradeTo:['battalion','quadruplet'],
  },
  battleship:{ bodybarrels:{ barrelOne:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:-30/180*Math.PI, x:0.9, barrelType:"drone", }, barrelTwo:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:-150/180*Math.PI, x:0.9, barrelType:"drone", }, barrelThree:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle: 90/180*Math.PI, x:0.9, barrelType:"drone", }, },
    upgradeTo:['mothership'],
  },
  remedy: { auraSpecialty: "heal", auraSize: 7.5,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.75, }, assetTwo: { type: "above", sides: 8, color: "rgba(56,183,100)", outline: "rgba(26,153,70)", size: 0.375, }, },
    upgradeTo: ['fabricator'],
  },
  blizzard: { auraSpecialty: "freeze", auraSize: 6,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(105, 104, 104)", outline: "rgb(79, 78, 78)", size: 0.65, }, assetTwo: { type: "above", sides: 0, color: "rgba(150, 208, 227)", outline: "rgba(132, 190, 209)", size: 0.3, }, },
    upgradeTo: ['snowstorm','juggernaut'],
  },
  flare: { auraSpecialty: "damaging", auraSize: 7,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.8, }, assetTwo: { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.4, }, },
    upgradeTo: ['foundry','juggernaut','inferno'],
  },

  //tier 5
  ziggurat: { assets:{ assetOne: { type:"above", sides:8, color:"default", outline:"default", size:1.1, }, assetTwo:{ type:"above", sides:6, color:"default", outline:"default", size:0.8, }, assetThree:{ type:"above", sides:4, color:"default", outline:"default", size:0.4, }, },
    upgradeTo:[],
  },
  bombard:{
    turretBaseSize: 0.8,
    bodybarrels:{ barrelOne:{ barrelWidth:1.1, barrelHeight:2, additionalAngle:0, x:0, barrelType:"bullet", }, },
    upgradeTo:[],
  },
  saw: { assets: { assetOne: { type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.8, }, },
    upgradeTo: [],
  },
  bastion:{ assets: { assetOne: { type: "under", sides: 5, color: "#5F676C", outline: "#41494E", size: 1.9, angle: -18, }, assetTwo: { type: "above", sides: 8, color: "default", outline: "default", size: 1.3, }, assetThree: { type: "above", sides: 6, color: "default", outline: "default", size: 0.9, }, },
    turretBaseSize:0.6,
    bodybarrels:{ barrelOne:{ barrelWidth:0.8, barrelHeight:1.4, additionalAngle:0, x:0, barrelType:"bullet", }, },
    upgradeTo:[],
  },
  battalion: {
    turretBaseSize: 0.6,
    bodybarrels: { barrelOne:{ barrelWidth:0.5, barrelHeight:1.05, additionalAngle:0, x:-0.3, barrelType:"bullet", }, barrelTwo:{ barrelWidth:0.5, barrelHeight:1.05, additionalAngle:0, x:0.3, barrelType:"bullet", }, barrelThree:{ barrelWidth:0.5, barrelHeight:1.25, additionalAngle:0, x:0, barrelType:"bullet", }, },
    assets: { assetOne: { type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.6, }, },
    upgradeTo: [],
  },
  foundry: { auraSpecialty: "damaging", auraSize: 6,
    assets: { assetThree: { type: "under", sides: 4, color: "#5F676C", outline: "#41494E", size: 1.6, }, assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.75, }, assetTwo: { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.375, }, },
    upgradeTo: [],
  },
  quadruplet:{
    turretBaseSize:0.65,
    bodybarrels:{ barrelOne:{ barrelWidth:0.4, barrelHeight:1.4, additionalAngle:0, x:0.4, barrelType:"bullet", }, barrelTwo:{ barrelWidth:0.4, barrelHeight:1.4, additionalAngle:0, x:-0.4, barrelType:"bullet", }, barrelThree:{ barrelWidth:0.4, barrelHeight:1.1, additionalAngle:0, x:-0.2, barrelType:"bullet", }, barrelFour:{ barrelWidth:0.4, barrelHeight:1.1, additionalAngle:0, x:0.2, barrelType:"bullet", }, },
    upgradeTo:[],
  },
  mothership:{ bodybarrels:{ barrelOne:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:45/180*Math.PI, x:0.9, barrelType:"drone", }, barrelTwo:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:-45/180*Math.PI, x:0.9, barrelType:"drone", }, barrelThree:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:135/180*Math.PI, x:0.9, barrelType:"drone", }, barrelFour:{ barrelWidth:0.8, barrelHeight:0.8, additionalAngle:-135/180*Math.PI, x:0.9, barrelType:"drone", }, },
    upgradeTo:[],
  },
  fabricator: { auraSpecialty: "heal", auraSize: 8,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.9, }, assetTwo: { type: "above", sides: 8, color: "rgba(56,183,100)", outline: "rgba(26,153,70)", size: 0.45, }, },
    upgradeTo: [],
  },
  snowstorm: { auraSpecialty: "freeze", auraSize: 8,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(105, 104, 104)", outline: "rgb(79, 78, 78)", size: 0.9, }, assetTwo: { type: "above", sides: 0, color: "rgba(150, 208, 227)", outline: "rgba(132, 190, 209)", size: 0.45, }, },
    upgradeTo: [],
  },
  juggernaut: { auraSpecialty: "attraction", auraSize: 8,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.9, }, assetTwo: { type: "above", sides: 0, color: "rgba(120, 118, 194)", outline: "rgba(90, 88, 164)", size: 0.45, }, },
    upgradeTo: [],
  },
  inferno: { auraSpecialty: "damaging", auraSize: 8,
    assets: { assetOne: { type: "above", sides: 0, color: "rgb(153,153,151)", outline: "rgb(122,124,123)", size: 0.9, }, assetTwo: { type: "above", sides: 0, color: "rgb(253,118,118)", outline: "rgb(222,88,88)", size: 0.45, }, },
    upgradeTo: [],
  },


//remove some upgrades, and fix celestials later
  mono:{
    turretBaseSize:0.6,
    bodybarrels:{ barrelOne:{ barrelWidth:0.8, barrelHeight:1.2, additionalAngle:0, x:0, barrelType:"bullet", }, },
    upgradeTo:['bastion','turret','armory'],
  },
  propeller:{ assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", size:0.3, }, },
    upgradeTo:['thruster'],
  },
  thruster:{ assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", size:0.4, }, },
    upgradeTo:['launcher'],
  },
  launcher:{ assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", size:0.5, }, },
    upgradeTo:['rocketer'],
  },
  rocketer:{ assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", size:0.6, }, },
    upgradeTo:[],
  },
  oven:{ eternal:"yes", assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.7, }, assetTwo:{ type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.4, }, },
    upgradeTo:['heliosphere','corvus'],
  },
  chainsaw:{ eternal:"yes", assets:{ assetOne:{ type:"under", sides:8, color:"grey", outline:"dimgrey", outlineThickness:5, size:1.2, }, },
    upgradeTo:['blade'],
  },
  blade:{ eternal:"yes", assets:{ assetOne:{ type:"under", sides:8, color:"#383838", outline:"black", outlineThickness:5, size:1.3, }, },
    upgradeTo:[],
  },
  pounder:{ eternal:"yes", assets:{ assetTwo:{ type:"under", sides:6, color:"slategrey", outline:"black", outlineThickness:5, size:1.4, }, assetOne:{ type:"under", sides:6, color:"dimgrey", outline:"black", outlineThickness:5, size:1.2, }, },
    upgradeTo:['chasm'],
  },
  lightning:{ eternal:"yes", assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.5, }, },
    upgradeTo:['firebolt'],
  },
  meteor:{ eternal:"yes", turretBaseSize:0.6, bodybarrels:{ barrelOne:{ barrelWidth:0.5, barrelHeight:1.2, additionalAngle:0, x:-0.3, barrelType:"bullet", }, barrelTwo:{ barrelWidth:0.5, barrelHeight:1.2, additionalAngle:0, x:0.3, barrelType:"bullet", }, },
    upgradeTo:['nebula'],
  },
  satellite:{ eternal:"yes", turretBaseSize:0.4, bodybarrels:{ barrelOne:{ barrelWidth:0.5, barrelHeight:1, additionalAngle:0, x:0, barrelType:"drone", }, },
    upgradeTo:['triton'],
  },
  heliosphere:{ eternal:"yes", assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.4, angle:0, x:0, y:0, }, assetTwo:{ type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.2, angle:0, x:0, y:0, }, assetThree:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.2, angle:0, x:0.7, y:0, }, assetFour:{ type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.1, angle:0, x:0.7, y:0, }, assetFive:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.2, angle:0, x:-0.4, y:-0.6, }, assetSix:{ type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.1, angle:0, x:-0.4, y:-0.6, }, assetSeven:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.2, angle:0, x:-0.4, y:0.6, }, assetEight:{ type:"above", sides:0, color:"rgb(250,112,112)", outline:"rgba(227,61,61)", outlineThickness:5, size:0.1, angle:0, x:-0.4, y:0.6, }, },
    upgradeTo:[],
  },
  corvus:{ eternal:"yes", assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.8, }, assetTwo:{ type:"above", sides:8, color:"rgba(56,183,100)", outline:"rgba(26,153,70)", outlineThickness:5, size:0.5, }, },
    upgradeTo:[],
  },
  firebolt:{ eternal:"yes", assets:{ assetOne:{ type:"above", sides:0, color:"rgb(105,104,104)", outline:"rgb(79,78,78)", outlineThickness:5, size:0.6, angle:0, x:0, y:0, }, },
    upgradeTo:[],
  },
  chasm:{ eternal:"yes", assets:{ assetOne:{ type:"under", sides:6, color:"#383838", outline:"black", outlineThickness:5, size:1.3, angle:0, x:0, y:0, }, },
    upgradeTo:[],
  },
  nebula:{ eternal:"yes", turretBaseSize:0.6, bodybarrels:{ barrelOne:{ barrelWidth:0.5, barrelHeight:1.2, additionalAngle:0, x:-0.3, barrelType:"bullet", }, barrelTwo:{ barrelWidth:0.5, barrelHeight:1.2, additionalAngle:0, x:0.3, barrelType:"bullet", }, barrelThree:{ barrelWidth:0.5, barrelHeight:1.4, additionalAngle:0, x:0, barrelType:"bullet", }, },
    upgradeTo:[],
  },
  triton:{ eternal:"yes", turretBaseSize:0.5, bodybarrels:{ barrelOne:{ barrelWidth:0.5, barrelHeight:1, additionalAngle:0, x:0, barrelType:"drone", }, barrelTwo:{ barrelWidth:0.3, barrelHeight:1.2, additionalAngle:0, x:0, barrelType:"drone", }, },
    upgradeTo:[],
  },
  primordial:{ eternal:"yes",
    upgradeTo:['oven','pounder','chainsaw','lightning','meteor','satellite'],
  },
};


export const weaponupgrades = {//barrelwidth and barrelheight seems to be twice the value of scenexe's, except trap, drone, and mine barrel widths are the same, and minion barrels are... weird (figure out scenexe's rendering later) (rocketer minion barrel width should be 1.5 times of scenexe most of the time)
  //unlike body barrels, weapon barrels are in terms of degree for angle, not radians
  //ALSO remember all barrels need to have different names, or else only one will render
  //tier 1
  node: { barrels: {},
    upgradeTo: ['mono','commander','trapper'],
  },
  //tier 2
  mono: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['duo','flank','split','single','alloy','guard','sniper'],
  },
  commander: { barrels: { barrelOne: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "drone", }, },
    upgradeTo: ['alloy','overseer','director','fusion'],
  },
  trapper: { barrels: { barrelOne: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, },
    upgradeTo: ['guard','fusion','gamma','blockade','rubble'],
  },
  //tier 3
  duo: { barrels: { barrelOne: { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0.5, barrelType: "bullet", }, },
    upgradeTo: ['trio','quad','arc','gunner'],
  },
  flank: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['quad','overlord','conglomerate','wake'],
  },
  split: { barrels: { barrelOne: { barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: -35, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: 35, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['trio','quad','arc','gunner','spread'],
  },
  single: { barrels: { barrelOne: { barrelWidth: 1.4, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['stream','destroyer','assassin','compound'],
  },
  alloy: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }, },
    upgradeTo: ['conglomerate','compound'],
  },
  guard: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: ['conglomerate','wake'],
  },
  sniper: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['wake','destroyer','assassin'],
  },
  overseer: { barrels: { barrelOne: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "drone", }, barrelTwo: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }, },
    upgradeTo: ['overlord','factory'],
  },
  director: { barrels: { barrelOne: { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "drone", }, },
    upgradeTo: ['compound','manager'],
  },
  fusion: { barrels: { barrelOne: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelTwo: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }, },
    upgradeTo: ['conglomerate'],
  },
  gamma: { barrels: { barrelOne: { barrelWidth: 0.85, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, },
    upgradeTo: ['beta','engineer'],
  },
  blockade: { barrels: { barrelOne: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelTwo: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: ['conglomerate','barricade','stockade'],
  },
  rubble: { barrels: { barrelOne: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelTwo: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 90, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelFour: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 270, x: 0, barrelType: "trap", }, },
    upgradeTo: ['scrap'],
  },
  //tier 4
  trio: { barrels: { barrelOne: { barrelWidth: 0.8, barrelHeight: 1.6, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.8, barrelHeight: 1.6, additionalAngle: 0, x: 0.5, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['knockback','quadro','penta','streamliner','industry'],
  },
  quad: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 270, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['octo','horizon'],
  },
  arc: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 45, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 2, additionalAngle: -45, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 2, additionalAngle: -90, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['penta','octo','horizon','disperse'],
  },
  gunner: { barrels: { barrelOne: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: -0.3, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: 0.3, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.4, barrelHeight: 1.2, additionalAngle: 0, x: -0.8, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.4, barrelHeight: 1.2, additionalAngle: 0, x: 0.8, barrelType: "bullet", }, },
    upgradeTo: ['quadro','streamliner','horizon','minigun'],
  },
  overlord: { barrels: { barrelOne: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "drone", }, barrelTwo: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: -120, x: 0, barrelType: "drone", }, barrelThree: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 120, x: 0, barrelType: "drone", }, },
    upgradeTo: ['emperor','hatcher'],
  },
  conglomerate: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 120, x: 0, barrelType: "drone", }, barrelFour: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: -120, x: 0, barrelType: "drone", }, },
    upgradeTo: ['amalgam'],
  },
  wake: { barrels: { barrelOne: { barrelWidth: 0.8, barrelHeight: 1.8, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.6, additionalAngle: -140, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.6, additionalAngle: 140, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['wave'],
  },
  spread: { barrels: { barrelSix: { barrelWidth: .5, barrelHeight: 1.4, additionalAngle: -60, x: 0, barrelType: "bullet", }, barrelSeven: { barrelWidth: .5, barrelHeight: 1.4, additionalAngle: 60, x: 0, barrelType: "bullet", }, barrelOne: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 40, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: -40, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: 20, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: -20, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['penta','horizon','disperse'],
  },
  stream: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['flamethrower'],
  },
  destroyer: { barrels: { barrelOne: { barrelWidth: 1.6, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['annihilator','manufacturer','hybrid'],
  },
  assassin: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2.5, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['streamliner','marksman'],
  },
  compound: { barrels: { barrelOne: { barrelWidth: 1.4, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: .7, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }, },
    upgradeTo: ['hybrid'],
  },
  factory: { barrels: { barrelOne: { barrelWidth: .75, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "minion", }, },
    upgradeTo: ['industry','manufacturer','hatcher'],
  },
  manager: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "drone", }, },
    upgradeTo: ['manufacturer','hybrid','executive'],
  },
  beta: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, },
    upgradeTo: ['alpha','raider'],
  },
  engineer: { barrels: { barrelOne: { barrelWidth: .75, barrelHeight: 1.9, additionalAngle: 0, x: 0, barrelType: "mine", }, },
    upgradeTo: ['raider','arsenal','mechanic','detonator'],
  },
  barricade: { barrels: { barrelTwo: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.65, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, },
    upgradeTo: ['wave','arsenal','riot'],
  },
  stockade: { barrels: { barrelOne: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelTwo: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 120, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: -120, x: 0, barrelType: "trap", },},
    upgradeTo: ['mechanic','palisade'],
  },
  scrap: { barrels: { barrelOne: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelTwo: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 60, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "trap", }, barrelFour: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelFive: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "trap", }, barrelSix: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 300, x: 0, barrelType: "trap", }, },
    upgradeTo: ['shrapnel'],
  },
  //tier 5
  knockback: { barrels: { barrelOne: { barrelWidth: 0.8, barrelHeight: 1.5, additionalAngle: 0, x: -0.6, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.8, barrelHeight: 1.5, additionalAngle: 0, x: 0.6, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  quadro: { barrels: { barrelOne: { barrelWidth: 0.6, barrelHeight: 2, additionalAngle: 0, x: 0.65, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.6, barrelHeight: 2, additionalAngle: 0, x: -0.65, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.6, barrelHeight: 1.6, additionalAngle: 0, x: 0.3, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.6, barrelHeight: 1.6, additionalAngle: 0, x: -0.3, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  penta: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 1.6, additionalAngle: 40, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.6, additionalAngle: -40, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: 20, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: -20, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  streamliner: { barrels: { barrelOne: { barrelWidth: 0.8, barrelHeight: 2.6, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.8, barrelHeight: 2.4, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.8, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 0.8, barrelHeight: 1.8, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 0.8, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelSeven: { barrelWidth: 0.8, barrelHeight: 1.4, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  industry: { barrels: { barrelOne: { barrelWidth: .7, barrelHeight: 2.2, additionalAngle: 0, x: -0.5, barrelType: "minion", }, barrelTwo: { barrelWidth: .7, barrelHeight: 2.2, additionalAngle: 0, x: 0.5, barrelType: "minion", }, },
    upgradeTo: [],
  },
  octo: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 45, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 135, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 225, x: 0, barrelType: "bullet", }, barrelSeven: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 270, x: 0, barrelType: "bullet", }, barrelEight: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 315, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  horizon: { barrels: { barrelOne: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 22.5, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: -22.5, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 45, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: -45, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 67.5, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: -67.5, x: 0, barrelType: "bullet", }, barrelSeven: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "bullet", }, barrelEight: { barrelWidth: 1, barrelHeight: 2, additionalAngle: -90, x: 0, barrelType: "bullet", }, barrelNine: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  disperse: { barrels: { barrelOne: { barrelWidth: .5, barrelHeight: 1.4, additionalAngle: -75, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: .5, barrelHeight: 1.4, additionalAngle: 75, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: -60, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 60, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: -45, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: 45, x: 0, barrelType: "bullet", }, barrelSeven: { barrelWidth: .5, barrelHeight: 2, additionalAngle: -30, x: 0, barrelType: "bullet", }, barrelEight: { barrelWidth: .5, barrelHeight: 2, additionalAngle: 30, x: 0, barrelType: "bullet", }, barrelNine: { barrelWidth: .5, barrelHeight: 2.2, additionalAngle: -15, x: 0, barrelType: "bullet", }, barrelTen: { barrelWidth: .5, barrelHeight: 2.2, additionalAngle: 15, x: 0, barrelType: "bullet", }, barrelEleven: { barrelWidth: 1, barrelHeight: 2.4, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  minigun: { barrels: { barrelOne: { barrelWidth: 0.4, barrelHeight: 2.4, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.4, barrelHeight: 2.4, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.4, barrelHeight: 2.4, additionalAngle: 0, x: 0.5, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, barrelFive: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 0.4, barrelHeight: 1.6, additionalAngle: 0, x: 0.5, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  emperor: { barrels: { barrelOne: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "drone", }, barrelTwo: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: -90, x: 0, barrelType: "drone", }, barrelThree: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 90, x: 0, barrelType: "drone", }, barrelFour: { barrelWidth: 0.5, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }, },
    upgradeTo: [],
  },
  hatcher: { barrels: { barrelOne: { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: 0, x: 0, barrelType: "minion", }, barrelTwo: { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: 120, x: 0, barrelType: "minion", }, barrelThree: { barrelWidth: .5, barrelHeight: 1.8, additionalAngle: -120, x: 0, barrelType: "minion", }, },
    upgradeTo: [],
  },
  amalgam: { barrels: { barrelOne: { barrelWidth: .8, barrelHeight: 2, additionalAngle: 0, x: 0.5, barrelType: "bullet", }, barrelTwo: { barrelWidth: .8, barrelHeight: 2, additionalAngle: 0, x: -0.5, barrelType: "bullet", }, barrelThree: { barrelWidth: .65, barrelHeight: 1.5, additionalAngle: -15, x: -0.4, barrelType: "trap", }, barrelFour: { barrelWidth: .65, barrelHeight: 1.5, additionalAngle: 15, x: 0.4, barrelType: "trap", }, barrelFive: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: 140, x: 0, barrelType: "drone", }, barrelSix: { barrelWidth: .5, barrelHeight: 1.6, additionalAngle: -140, x: 0, barrelType: "drone", }, },
    upgradeTo: [],
  },
  wave: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: -150, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: 150, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: .65, barrelHeight: 2.1, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelFour: { barrelWidth: .65, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelFive: { barrelWidth: .8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  flamethrower: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  annihilator: { barrels: { barrelOne: { barrelWidth: 2, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  manufacturer: { barrels: { barrelOne: { barrelWidth: 1.1, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "minion", }, },
    upgradeTo: [],
  },
  hybrid: { barrels: { barrelOne: { barrelWidth: 1.6, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.8, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "drone", }, },
    upgradeTo: [],
  },
  marksman: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2.8, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  executive: { barrels: { barrelOne: { barrelWidth: 1.5, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "drone", }, },
    upgradeTo: [],
  },
  alpha: { barrels: { barrelOne: { barrelWidth: 1.5, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
  detonator: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "mine", }, },
    upgradeTo: [],
  },
  raider: { barrels: { barrelOne: { barrelWidth: .9, barrelHeight: 1.7, additionalAngle: 0, x: 0, barrelType: "mine", }, },
    upgradeTo: [],
  },
  arsenal: { barrels: { barrelOne: { barrelWidth: .6, barrelHeight: 2.2, additionalAngle: 0, x: 0, barrelType: "mine", }, barrelTwo: { barrelWidth: .6, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "mine", }, },
    upgradeTo: [],
  },
  mechanic: { barrels: { barrelOne: { barrelWidth: .55, barrelHeight: 1.7, additionalAngle: 0, x: 0, barrelType: "mine", }, barrelTwo: { barrelWidth: .55, barrelHeight: 1.7, additionalAngle: 120, x: 0, barrelType: "mine", }, barrelThree: { barrelWidth: .55, barrelHeight: 1.7, additionalAngle: -120, x: 0, barrelType: "mine", }, },
    upgradeTo: [],
  },
  riot: { barrels: { barrelOne: { barrelWidth: 0.65, barrelHeight: 2.5, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelTwo: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.65, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
  palisade: { barrels: { barrelOne: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelTwo: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: -90, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 90, x: 0, barrelType: "trap", }, barrelFour: { barrelWidth: 0.65, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
  shrapnel: { barrels: { barrelOne: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelTwo: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 45, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 90, x: 0, barrelType: "trap", }, barrelFour: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 135, x: 0, barrelType: "trap", }, barrelFive: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelSix: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 225, x: 0, barrelType: "trap", }, barrelSeven: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 270, x: 0, barrelType: "trap", }, barrelEight: { barrelWidth: 0.45, barrelHeight: 1.5, additionalAngle: 315, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
//unwanted tanks + celestial
/*
  delta: { barrels: { barrelOne: { barrelWidth: 0.75, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "trap", }, },
    upgradeTo: ['gamma','blockade','minelayer','warden'],
  },
  targeter: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['streamliner'],
  },
  protector: { barrels: { barrelOne: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 90, x: 0, barrelType: "drone", }, barrelTwo: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: -90, x: 0, barrelType: "drone", }, },
    upgradeTo: ['king'],
  },
  blaster: { barrels: { barrelOne: { barrelWidth: 0.4, barrelHeight: 2, additionalAngle: 0, x: -0.6, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.4, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.4, barrelHeight: 2, additionalAngle: 0, x: 0.6, barrelType: "bullet", }, },
    upgradeTo: ['minigun','knockback'],
  },
  jet: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['flamethrower'],
  },
  fighter: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: 90, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 150, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: -90, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 210, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['wave','amalgam'],
  },
  tyrant: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "drone", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: -72, x: 0, barrelType: "drone", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: 72, x: 0, barrelType: "drone", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: -144, x: 0, barrelType: "drone", }, barrelFive: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: 144, x: 0, barrelType: "drone", }, },
    upgradeTo: [],
  },
  industry: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "minion", }, barrelTwo: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "minion", }, barrelThree: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "minion", }, },
    upgradeTo: [],
  },
  battler: { barrels: { barrelOne: { barrelWidth: 0.7, barrelHeight: 1.8, additionalAngle: -15, x: -0.6, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.4, barrelHeight: 2, additionalAngle: 0, x: -0.3, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.4, barrelHeight: 2, additionalAngle: 0, x: 0.3, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.7, barrelHeight: 1.8, additionalAngle: 15, x: 0.6, barrelType: "bullet", }, barrelFive: { barrelWidth: 1 , barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
  pinnace: { barrels: { barrelOne: { barrelWidth: 0.4, barrelHeight: 1.4, additionalAngle: 0, x: 0.3, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.4, barrelHeight: 1.4, additionalAngle: 0, x: -0.3, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.4, barrelHeight: 1.8, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.75, barrelHeight: 2.25, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelFive: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
  cyclone: { barrels: { barrelOne: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 30, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 60, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 90, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 120, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 150, x: 0, barrelType: "bullet", }, barrelSeven: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "bullet", }, barrelEight: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 210, x: 0, barrelType: "bullet", }, barrelNine: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 240, x: 0, barrelType: "bullet", }, barrelTen: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 270, x: 0, barrelType: "bullet", }, barrelEleven: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 300, x: 0, barrelType: "bullet", }, barrelTwelve: { barrelWidth: 0.67, barrelHeight: 1.6, additionalAngle: 330, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  conquerer: { barrels: { barrelOne: { barrelWidth: 0.8, barrelHeight: 3, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.8, barrelHeight: 2.75, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.8, barrelHeight: 2.5, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.8, barrelHeight: 2.25, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 0.8, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 0.8, barrelHeight: 1.75, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelSeven: { barrelWidth: 0.8, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  hunter: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 3.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  hex: { barrels: { barrelOne: { barrelWidth: 1.2, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1.2, barrelHeight: 2, additionalAngle: 60, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1.2, barrelHeight: 2, additionalAngle: 120, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1.2, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1.2, barrelHeight: 2, additionalAngle: 240, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 1.2, barrelHeight: 2, additionalAngle: 300, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  guardian: { barrels: { barrelOne: { barrelWidth: 1.1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.9, additionalAngle: 190, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.9, additionalAngle: 170, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 2.05, additionalAngle: 180, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  comet: { barrels: { barrelSix: { barrelWidth: 1, barrelHeight: 1.34, additionalAngle: 245, x: 0, barrelType: "bullet", }, barrelSeven: { barrelWidth: 1, barrelHeight: 1.34, additionalAngle: -245, x: 0, barrelType: "bullet", }, barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 135, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.72, additionalAngle: 155, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 225, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 1.72, additionalAngle: 205, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  wave: { barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: 100, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 145, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: -100, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: -145, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
  manufacturer: { barrels: { barrelOne: { barrelWidth: 1 * 1.3, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "mine", }, },
    upgradeTo: [],
  },
  CEO: { barrels: { barrelOne: { barrelWidth: 2, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "drone", }, },
    upgradeTo: [],
  },
  */
  hailstorm: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 120, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 240, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['thunderstorm','cosmetic'],
  },
  bunker: { eternal: "yes", barrels: { barrelTwo: { barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "trap", }, barrelFour: { barrelWidth: 0.5, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "trap", }, },
    upgradeTo: ['vault','asteroid','dynamite'],
  },
  chaos: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 0.67, barrelHeight: 1.3, additionalAngle: 90, x: 0, barrelType: "drone", }, barrelTwo: { barrelWidth: 0.67, barrelHeight: 1.3, additionalAngle: -90, x: 0, barrelType: "drone", }, },
    upgradeTo: ['mayhem','tavros'],
  },
  bombshell: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 1.5, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1.5, barrelHeight: 1.2, additionalAngle: 120, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1.5, barrelHeight: 1.2, additionalAngle: 240, x: 0, barrelType: "bullet", }, },
    upgradeTo: ['demolisher'],
  },
  warrior: { eternal: "yes", barrels: { barrelEight: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 0, x: 0, barrelType: "drone", }, barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: 120, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: -120, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: ['veteran'],
  },
  thunderstorm: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 180, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 60, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 120, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 240, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 0.9, barrelHeight: 1.3, additionalAngle: 300, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  cosmetic: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 0.9, barrelHeight: 1.6, additionalAngle: 180, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.9, barrelHeight: 1.6, additionalAngle: 60, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.8, barrelHeight: 1.3, additionalAngle: 120, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 0.8, barrelHeight: 1.3, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 0.8, barrelHeight: 1.3, additionalAngle: 240, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 0.9, barrelHeight: 1.6, additionalAngle: 300, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  vault: { eternal: "yes", barrels: { barrelTwo: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 60, x: 0, barrelType: "trap", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 120, x: 0, barrelType: "trap", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 180, x: 0, barrelType: "trap", }, barrelFive: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 240, x: 0, barrelType: "trap", }, barrelSix: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 300, x: 0, barrelType: "trap", }, barrelOne: { barrelWidth: 1, barrelHeight: 1.2, additionalAngle: 0, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
  asteroid: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "mine", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "mine", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "mine", }, },
    upgradeTo: [],
  },
  mayhem: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 0.67, barrelHeight: 1.3, additionalAngle: 90, x: 0, barrelType: "drone", }, barrelTwo: { barrelWidth: 0.67, barrelHeight: 1.3, additionalAngle: -90, x: 0, barrelType: "drone", }, barrelThree: { barrelWidth: 0.67, barrelHeight: 1.3, additionalAngle: 0, x: 0, barrelType: "drone", }, barrelFour: { barrelWidth: 0.67, barrelHeight: 1.3, additionalAngle: 180, x: 0, barrelType: "drone", }, },
    upgradeTo: [],
  },
  dynamite: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "mine", }, barrelTwo: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 120, x: 0, barrelType: "mine", }, barrelThree: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 240, x: 0, barrelType: "mine", }, },
    upgradeTo: [],
  },
  tarvos: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 0, x: 0, barrelType: "minion", }, barrelTwo: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 120, x: 0, barrelType: "minion", }, barrelThree: { barrelWidth: 0.75, barrelHeight: 1.5, additionalAngle: 240, x: 0, barrelType: "minion", }, },
    upgradeTo: [],
  },
  demolisher: { eternal: "yes", barrels: { barrelOne: { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 60, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 120, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 180, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 240, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 1.5, barrelHeight: 1.3, additionalAngle: 300, x: 0, barrelType: "bullet", }, },
    upgradeTo: [],
  },
  veteran: { eternal: "yes", barrels: { barrelSeven: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 25, x: 0, barrelType: "drone", }, barrelEight: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: -25, x: 0, barrelType: "drone", }, barrelOne: { barrelWidth: 1, barrelHeight: 2, additionalAngle: 0, x: 0, barrelType: "bullet", }, barrelTwo: { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: 100, x: 0, barrelType: "bullet", }, barrelThree: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: 145, x: 0, barrelType: "bullet", }, barrelFour: { barrelWidth: 1, barrelHeight: 1.44, additionalAngle: -100, x: 0, barrelType: "bullet", }, barrelFive: { barrelWidth: 1, barrelHeight: 1.4, additionalAngle: -145, x: 0, barrelType: "bullet", }, barrelSix: { barrelWidth: 1, barrelHeight: 1.8, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: [],
  },
  eternal: { eternal: "yes",
    upgradeTo: ['hailstorm','bunker','chaos','bombshell','warrior'],
  },
  minesweeper: { barrels: { barrelOne: { barrelWidth: 0.4, barrelHeight: 1.4, additionalAngle: 0, x: -0.3, barrelType: "bullet", }, barrelTwo: { barrelWidth: 0.4, barrelHeight: 1.4, additionalAngle: 0, x: 0.3, barrelType: "bullet", }, barrelThree: { barrelWidth: 0.75, barrelHeight: 2, additionalAngle: 180, x: 0, barrelType: "trap", }, },
    upgradeTo: ['battler','pinnace'],
  },
};

export const bodyColors = {//side note: color when hit or have spawn protection has values in RGB is 20 higher)
  blue: {
    col: "#00B0E1",
    outline: "#0092C3",
  },
  green: {
    col: "#00E06C",
    outline: "#00C24E",
  },
  red: {
    col: "#F04F54",
    outline: "#b33b3f",
  },
  purple: {
    col: "#BE7FF5",
    outline: "#A061D7",
  },
  magenta: {
    col: "#D82BCF",
    outline: "#BA0DB1",
  },
  fallen: {
    col: "#C0C0C0",
    outline: "#A2A2A2",
  },
  eternal: {
    col: "#934c93",
    outline: "#660066",
  },
  celestial: {
    col: "#F177DD",
    outline: "#D359BF",
  },
  barrel: {
    col: "#999999",
    outline: "#7B7B7B",
  },
  asset: {
    col: "#5F676C",
    outline: "#41494E",
  },
  triangle: {
    col: "#FFE46B",
    outline: "#E1C64D",
  },
  square: {
    col: "#FC7676",
    outline: "#DE5858",
  },
  pentagon: {
    col: "#768CFC",
    outline: "#586EDE",
  },
  hexagon: {
    col: "#FCA644",
    outline: "#DE8826",
  },
  heptagon: {
    col: "#38B764",
    outline: "#1A9946",
  },
  octagon: {
    col: "#4A66BD",
    outline: "#2C489F",
  },
  nonagon: {
    col: "#5D275D",
    outline: "#3F093F",
  },
  decagon: {
    col: "#1A1C2C",
    outline: "#00000E",
  },
  hendecagon: {
    col: "#060011",
    outline: "#000000",
  },
  dodecagon: {
    col: "#403645",
    outline: "#221827",
  },
  tridecagon: {
    col: "#EDEDFF",
    outline: "#CFCFE1",
  },
  tetradecagon: {
    col: "#000000",
    outline: "#000000",
  },
  transparent: {
    col: "transparent",
    outline: "transparent",
  }
};


export const botcolors = {
  //get colors based on dune mob name
  Cluster: {
    color: "#00ffff",
    outline: "#09d3fb",
    specialty: "",
    static: "no",
    minion: "no",
  },
  Pursuer: {
    color: "#00ffff",
    outline: "#09d3fb",
    specialty: "",
    static: "no",
    minion: "yes",
  },
  Crasher: {
    color: "#00ffff",
    outline: "#09d3fb",
    specialty: "",
    static: "no",
    minion: "yes",
  },
  Champion: {
    color: "#00ffff",
    outline: "#09d3fb",
    specialty: "",
    static: "no",
    minion: "no",
  },
  Infestor: {
    color: "#916f6f",
    outline: "#6c5353",
    specialty: "",
    static: "no",
    minion: "no",
  },
  Pillbox: {
    color: "#916f6f",
    outline: "#6c5353",
    specialty: "bullet knockback",
    static: "no",
    minion: "yes",
  },
  Leech: {
    color: "#916f6f",
    outline: "#6c5353",
    specialty: "lifesteal",
    static: "no",
    minion: "yes",
  },

  "Cavern Protector": {
    color: "#FFE46B",
    outline: "#E1C64D",
    specialty: "",
    static: "no",
    minion: "no",
  },
  "Abyssling": {
    color: "#FFE46B",
    outline: "#E1C64D",
    specialty: "",
    static: "no",
    minion: "no",
  },


  Legion: {
    color: "#e9ac7a",
    outline: "#d99b68",
    specialty: "",
    static: "no",
    minion: "no",
  },
  Booster: {
    color: "#e9ac7a",
    outline: "#d99b68",
    specialty: "",
    static: "no",
    minion: "no",
  },
  'Mega-Crasher': {
    color: "#bf3939",
    outline: "#B22222",
    specialty: "",
  },
  Spike: {
    color: "#123573",
    outline: "#0c2859",
    specialty: "it hurts",
  },
  Mortar: {
    color: "#001a47",
    outline: "#001333",
    specialty: "it hurts even more",
  },
  Rogue: {
    color: "#731582",
    outline: "#581063",
    specialty: "lifesteal",
  },
  Shield: {
    color: "#c79b4e",
    outline: "#a6803d",
    specialty: "bullet knockback",
  },
  Grower: {
    color: "#9400D3",
    outline: "#62008B",
    specialty: "grows when it deals damage",
  },
  Protector: {
    color: "#D5CE67",
    outline: "#ABA552",
    specialty: "sniper",
  },
  Boss: {
    color: "#86775F",
    outline: "#404040",
    specialty: "rarely spawns",
  },
  King: {
    color: "#47048a",
    outline: "#830ff7",
    specialty: "high health",
  },
  Titan: {
    color: "#a03333",
    outline: "#791a1a",
    specialty: "superior health",
  },
  Sultan: {
    color: "#0003b3",
    outline: "#00027a",
    specialty: "Upgraded Titan",
  },
  Beast: {
    color: "#B5D648",
    outline: "#5B692C",
    specialty: "Insane health",
  },
  Wall: {
    color: "#3b2b20",
    outline: "#8a6950",
    specialty: "bullet knockback",
  },

  Rock: {
    color: "#909090",
    outline: "#5c5c5c",
    specialty: "",
    static: "yes",
    minion: "no",
  },
  Gravel: {
    color: "#909090",
    outline: "#5c5c5c",
    specialty: "",
    static: "yes",
    minion: "no",
  },
  Boulder: {
    color: "#505250",
    outline: "#000000",
    specialty: "",
    static: "yes",
    minion: "no",
  },
  Mountain: {
    color: "#b8683b",
    outline: "#87563a",
    specialty: "",
    static: "yes",
    minion: "no",
  },
  Cactus: {
    color: "#60b560",
    outline: "#428042",
    specialty: "",
    static: "yes",
    minion: "no",
  },
};